print("Hello, how are you?")
print("Single Quote: Hello, how \'are you?")
print("Backslash: Hello, how \\are you?")
print("New line: Hello, how \nare you?")
print("Carriage return:\n Hello, how \rare you?")
print("Tab: Hello, how \tare you?")
print("Backspace: Hello, how \bare you?")
print("Octal value: \110\145\154\154\157")
print("Hex value: \x48\x65\x6c\x6c\x6f")